upstream upstream_{{proxy.name}} {
  server {{proxy.server}};
}

server {
  listen 443 ssl;
  listen [::]:443 ssl;
  server_name {{proxy.name}}.{{domain}};

  location {{proxy.location}} {
    proxy_pass upstream_{{proxy.name}};
  }
}
