---
- name: Install DNS packages
  apt:
    name: "{{packages}}"
  vars:
    packages:
    - bind9
    - bind9utils
    - bind9-doc
  become: yes
- name: Create DNS directories
  file:
    path: "{{item}}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
  - "{{dns.bin_dir}}"
  - "{{dns.etc_dir}}"
  - "{{dns.etc_zones_dir}}"
  - "{{dns.etc_forward_zones_dir}}"
  - "{{dns.etc_reverse_zones_dir}}"
  - "{{dns.var_dir}}"
  - "{{dns.var_zones_dir}}"
  - "{{dns.var_forward_zones_dir}}"
  - "{{dns.domain_lists_dir}}"
  become: yes
- name: Copy bind9 defaults file
  copy:
    src: bind9
    dest: /etc/default/bind9
    owner: root
    group: root
    mode: 0644
  become: yes
- name: Render named options config template
  template:
    src: named.conf.options
    dest: /etc/bind/named.conf.options
    owner: root
    group: root
    mode: 0644
  become: yes
- name: Render named local config template
  template:
    src: named.conf.local
    dest: /etc/bind/named.conf.local
    owner: root
    group: root
    mode: 0644
  become: yes
- name: Render named forward zone templates
  template:
    src: db.forward_zone
    dest: "{{dns.etc_forward_zones_dir}}/{{forward_zone.name}}.db"
    owner: root
    group: root
    mode: 0644
  vars:
    forward_zone: "{{item}}"
  loop: "{{dns.zones}}"
  become: yes
- name: Render named reverse zone templates
  template:
    src: db.reverse_zone
    dest: "{{dns.etc_reverse_zones_dir}}/{{reverse_zone.name}}.db"
    owner: root
    group: root
    mode: 0644
  vars:
    forward_zone: "{{item.0}}"
    reverse_zone: "{{item.1}}"
  loop: "{{dns.zones | subelements('reverse_zones', {'skip_missing': True})}}"
  become: yes
- name: Create domain lists file
  copy:
    content: "{{dns.domain_list_zones | to_nice_yaml(indent=2, width=80)}}"
    dest: "{{dns.domain_lists_file}}"
    owner: root
    group: root
    mode: 0644
  become: yes
- name: Render domain list zones bin template
  template:
    src: domain-list-zones.py
    dest: "{{dns.domain_list_zones_bin}}"
    owner: root
    group: root
    mode: 0755
  become: yes
- name: Add domain list zones bin to cron
  file:
    src: "{{dns.domain_list_zones_bin}}"
    dest: /etc/cron.daily/router.dns.domain-lists
    state: link
    owner: root
    group: root
    mode: 0755
  become: yes
- name: Generate domain list zone files
  command: >
    {{dns.domain_list_zones_bin}} --no-reload-bind
  become: yes
- name: Check named config
  command: named-checkconf /etc/bind/named.conf
  become: yes
- name: Check named forward zones
  command: >
    named-checkzone
      {{item.domain}}
      {{dns.etc_forward_zones_dir}}/{{item.name}}.db
  loop: "{{dns.zones}}"
  become: yes
- name: Check named reverse zones
  command: >
    named-checkzone
      {{reverse_zone.ip_address.split(".") | reverse | join(".")}}.in-addr.arpa
      {{dns.etc_reverse_zones_dir}}/{{reverse_zone.name}}.db
  vars:
    forward_zone: "{{item.0}}"
    reverse_zone: "{{item.1}}"
  loop: "{{dns.zones | subelements('reverse_zones', skip_missing=True)}}"
  become: yes
- name: Enable BIND9 service
  systemd:
    name: bind9.service
    state: started
    enabled: yes
  become: yes
- name: Reload BIND9 service
  systemd:
    name: bind9.service
    state: reloaded
  become: yes
